version: '3.8'

services:
  username-checker:
    build: .
    container_name: username-checker-node
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PORT=5000
      - NODE_ENV=production
